version: '2.1'
orbs:
  node: circleci/node@4.2.1
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: node --version
      
      - run:
          name: Running k6 tests
          command: |-
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
            echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install k6
          
      - run: npm install
      - run: npm i k6-html-reporter
      - run: npm run performance; node report.js 

      - store_artifacts:
          path: /root/project/report    
          destination: report
        
        
workflows:
  test_my_app:
    jobs:
      - install-node-example
