default: &defaults
  parallelism: 1
  working_directory: ~/load_test_k6
k6_performance_tests: &k6_performance_tests
  run:
    name: Running k6 tests
    # Download the k6 docker image. Alternatively, download the k6 release binary
    # Mount a volume to access the folder and run the test
    command: |
      docker pull loadimpact/k6:latest
      docker run -i -v $HOME/my-project:/ci/ loadimpact/k6:latest run /ci/loadtests/performance-test.js
version: 2
jobs:
  run_performance_tests:
    <<: *defaults
    # Use `machine` executor because the Docker executor cannot mount volumes
    machine: true
    steps:
      - checkout
      - npm install
      - npm run performance; node report.js
      #- *k6_performance_tests

      - store_artifacts:
          path: /root/project/report    
          destination: report

workflows:
  version: 2
  build-and-test:
    jobs:
      - run_performance_tests