version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.14.0
    steps:
      - checkout
      - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
      - echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
      - apt-get update
      - apt-get install k6
      - node install npm 
      
      - run: node --version
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
     
      - run: npm run performance; node report.js
        
      - store_artifacts:
          path: /root/project/report    
          destination: report

